# Baibusu API Compose Example
# Updated Sep 5, 2025

services:
  api:
    image: apibackend:v1.0.8
    container_name: baibusu-api-backend
    restart: unless-stopped
    ports:
      - ${PORT}:3000
    networks:
      - baibusu
    environment:
      - DATABASE_URL=${DATABASE_URL} # Same username and password as below
      - APIKEY=${APIKEY} # Your super secret code
      - NODE_ENV=production # production, test (utilizes .env.test)
      - LOG_LEVEL=info # trace, debug, info, warn, error, fatal
networks:
  baibusu:
    external: true
