services:
  postgres:
    profiles: [dev, prod]
    image: postgres:17-trixie
    container_name: beta-api-db
    restart: unless-stopped
    ports:
      - 5432:5432 # Expose PostgreSQL port for development (remove in production)
    volumes:
      - dev_db_volume:/var/lib/postgresql/data # Persist database data in a Docker volume
      - ./scripts/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-baibusu}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-baibusu}
      POSTGRES_MULTIPLE_DATABASES: api, kazuko
    env_file:
      - .env # Load environment variables from the .env file

volumes:
  dev_db_volume:
    driver: local # Specify the volume driver for local persistence
